### ISSUE TITLE
Allow editing "website address"

### ISSUE THREAD

**Issue by tonglil** [mozilla-lockwise/lockwise-addon#329] opened 2019-07-02 21:39 UTC
Allow me to update the website address to `https` from `http`:

View:
<img width="379" alt="image" src="https://user-images.githubusercontent.com/3250776/60548494-107c6400-9cd7-11e9-98d6-99db409a948c.png">

Edit:
<img width="366" alt="image" src="https://user-images.githubusercontent.com/3250776/60548501-16724500-9cd7-11e9-977c-15c8baa7cc02.png">

Can only change other fields or delete. Need to update. There is no duplicate functionality.

**Comment by Eagle3386** [comment] 2019-10-11 13:53
Duplicate of #314.

**Comment by mnoorenberghe** [comment] 2020-06-06 07:20
Tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1578063

**Closed by mnoorenberghe** 2020-06-06 07:20 UTC

**Comment by hanyas** [comment] 2021-02-02 20:14
How is this still a thing!

**Comment by Eagle3386** [comment] 2021-02-02 21:11
Since this issue got closed & just right above your comment, there's a link to the corresponding Bugzilla entry, probably nobody from the officials will reply to you.
