### ISSUE TITLE
Doorhanger behaves badly if overflowed

### ISSUE THREAD

**Issue by 6a68** [mozilla-lockwise/lockwise-addon#257] opened 2019-05-21 17:52 UTC
When the Firefox window is narrow, the right-side toolbar buttons are collapsed into the '>>' overflow menu. In this view, the doorhanger is wider than usual, but our doorhanger content doesn't stretch to fit:

<img src="https://user-images.githubusercontent.com/96396/58118793-7513b180-7bb6-11e9-82b7-8beb2cdc0078.png" width="300">

**Comment by linuxwolf** [comment] 2019-05-21 20:08
duplicate of #152

**Closed by linuxwolf** 2019-05-21 20:08 UTC
