### ISSUE TITLE
Password generation

### ISSUE THREAD

**Issue by rogemus** [mozilla-lockwise/lockwise-addon#319] opened 2019-06-13 15:03 UTC
Hi, 
do you have plans for create some kind of password generation functionality in Lockwise? 

example from lastpass 
![Screenshot 2019-06-13 at 17 01 36](https://user-images.githubusercontent.com/9271549/59443861-06182a00-8dfd-11e9-89b4-0269ed648a77.png)

**Comment by linuxwolf** [comment] 2019-06-14 16:19
Thanks for the feedback.  Password generation is being actively worked as a feature in Firefox.  You can follow that work in [BMO-376674](https://bugzilla.mozilla.org/show_bug.cgi?id=376674).

**Comment by rogemus** [comment] 2019-06-17 13:56
@linuxwolf thx for your answer, that's great to hear 😃 

Do you have a plan to store data for more complete complex form eg. address with multiple fields?

**Comment by klausenbusk** [comment] 2019-07-29 18:42
Duplicate of https://github.com/mozilla-lockwise/lockwise-addon/issues/130

**Closed** 2019-10-14 21:08 UTC
